// ============================================
// Alladin – Final Decision Maker Node
// ============================================
// The hedge-fund manager who synthesizes all analyst inputs into
// a final INVEST / PASS / WAIT_MONITOR decision with full reasoning
// grounded in Benjamin Graham's "The Intelligent Investor" principles.
// ============================================

import { createLLM } from '../llm';
import type { AgentState, InvestmentDecision } from '../state';

const DISCLAIMER = `⚠️ DISCLAIMER: This report is generated by an AI system for educational and informational purposes only. It does NOT constitute financial advice, investment recommendation, or solicitation to buy or sell any security. Always consult a qualified financial advisor before making investment decisions. Past performance does not guarantee future results. Investing involves risk, including the possible loss of principal.`;

/**
 * decisionNode – Final investment decision synthesis.
 * Reads: company, fundamentals, sentiment, geopolitics, valuation
 * Writes: decision, status
 */
export async function decisionNode(state: AgentState): Promise<Partial<AgentState>> {
  console.log('[Decision] Synthesizing final verdict for:', state.company?.name || state.query);

  const name = state.company?.name || state.query;
  const ticker = state.company?.ticker || state.query;
  const currentPrice = state.company?.currentPrice || 0;

  // --- Collect all analyst outputs ---
  const fundScore = state.fundamentals?.score ?? 50;
  const sentimentScore = state.sentiment?.sentimentScore ?? 50;
  const marginOfSafety = state.valuation?.marginOfSafety ?? 0;
  const riskCount = state.geopolitics?.risks?.filter(
    (r) => r.severity === 'high' || r.severity === 'critical'
  ).length ?? 0;

  // --- Decision Logic (Fallback base + LLM) ---
  // Weighted scoring: Fundamentals 35%, Valuation 30%, Sentiment 20%, Geopolitics 15%
  const compositeScore =
    fundScore * 0.35 +
    (marginOfSafety > 0 ? Math.min(marginOfSafety * 2, 100) : Math.max(marginOfSafety, -100) + 100) / 2 * 0.30 +
    sentimentScore * 0.20 +
    Math.max(0, 100 - riskCount * 25) * 0.15;

  const fallbackAction = (compositeScore >= 45 && marginOfSafety >= -5) ? 'INVEST' : 'PASS';

  // --- Full LLM report generation ---
  let reasoning = '';
  let finalAction: 'INVEST' | 'PASS' = fallbackAction;
  let confidenceScore = Math.round(compositeScore);
  let targetPrice: number | null = state.valuation?.intrinsicValue ?? null;
  let stopLoss: number | null = currentPrice > 0 ? Math.round(currentPrice * 0.85 * 100) / 100 : null;

  try {
    const llm = createLLM({ temperature: 0.4, maxTokens: 2500 });


    const prompt = `You are a senior hedge fund manager and Benjamin Graham disciple making a final investment decision.

## Company Under Review
**${name}** (${ticker}) — Current Price: $${currentPrice.toFixed(2)}

## Analyst Reports Summary

### Fundamental Analysis (Score: ${fundScore}/100)
${state.fundamentals?.analysis?.slice(0, 800) || 'No fundamental analysis available.'}

Graham Checklist: ${state.fundamentals?.grahamChecklist?.filter(c => c.passed).length || 0}/${state.fundamentals?.grahamChecklist?.length || 10} criteria passed

### Sentiment Analysis (Score: ${sentimentScore}/100 — ${state.sentiment?.overallSentiment || 'neutral'})
${state.sentiment?.analysis?.slice(0, 600) || 'No sentiment analysis available.'}

### Geopolitical & Macro Analysis
${state.geopolitics?.analysis?.slice(0, 600) || 'No geopolitical analysis available.'}
High/Critical Risks: ${riskCount}

### Valuation Analysis
- Graham Formula Value: ${state.valuation?.grahamValue ? `$${state.valuation.grahamValue.toFixed(2)}` : 'N/A'}
- DCF Value: ${state.valuation?.dcfValue ? `$${state.valuation.dcfValue.toFixed(2)}` : 'N/A'}
- Intrinsic Value: ${state.valuation?.intrinsicValue ? `$${state.valuation.intrinsicValue.toFixed(2)}` : 'N/A'}
- Margin of Safety: ${marginOfSafety.toFixed(1)}%
${state.valuation?.analysis?.slice(0, 600) || ''}

## Scenario Analysis
- Bull: $${state.valuation?.scenarios?.bull?.price?.toFixed(2) || 'N/A'} — ${state.valuation?.scenarios?.bull?.reasoning?.slice(0, 100) || ''}
- Base: $${state.valuation?.scenarios?.base?.price?.toFixed(2) || 'N/A'}
- Bear: $${state.valuation?.scenarios?.bear?.price?.toFixed(2) || 'N/A'} — ${state.valuation?.scenarios?.bear?.reasoning?.slice(0, 100) || ''}

---

Now write the FINAL INVESTMENT REPORT. You must evaluate all the analyst reports and valuations above, and make the final decision to either INVEST or PASS yourself based on Benjamin Graham's rules. Structure it as follows:

# Investment Report: ${name} (${ticker})

## Executive Summary
A 2-3 sentence verdict.
*Note: If your decision is INVEST but there are geopolitical risks (high/critical risks > 0) or highly negative news sentiment (sentiment score < 30), you MUST add a highlighted caution warning here advising the investor to stay patient and delay execution/entry until near-term headwinds settle.*

## Decision: [INVEST / PASS]
Note: You MUST strictly only choose between "INVEST" or "PASS" as the final decision status. Do NOT output "WAIT & MONITOR" as a status.

## Key Reasoning
Apply Benjamin Graham's framework explicitly:
1. **Margin of Safety**: Is the current price sufficiently below intrinsic value?
2. **Intrinsic Value vs. Market Price**: Investment or speculation?
3. **Mr. Market**: Is the market emotional state working in our favor?
4. **Defensive vs. Enterprising**: Which type of Graham investor is this suitable for?
5. **Earnings Stability & Financial Strength**: Does the balance sheet inspire confidence?
*Note: If there are threats (geopolitical risks > 0 or sentiment score < 30) but your final decision is INVEST, clearly explain here why patience or waiting for the situation to stabilize is recommended before purchasing.*

## Risk-Reward Assessment
Asymmetry analysis across bull/base/bear cases.

## Conditions & Triggers
- If PASS: What would need to change for reconsideration?
- If INVEST: What is the ideal entry price, position sizing, and stop loss? If there are active threats, explicitly set trigger conditions based on those threats settling (e.g. "Wait until tariff negotiations resolve" or "Stay patient until news indicators turn positive").

## Sources & Confidence
List data sources and overall confidence level.

Write with the authority and rigor of a Warren Buffett annual letter. Be specific with numbers.`;

    const response = await llm.invoke(prompt);
    reasoning = typeof response.content === 'string' ? response.content : JSON.stringify(response.content);

    // Extract the final action from the LLM's response - strictly INVEST or PASS
    const decisionMatch = reasoning.match(/## Decision:\s*\*\*?(INVEST|PASS)\*\*?/i) || 
                          reasoning.match(/Decision:\s*\*\*?(INVEST|PASS)\*\*?/i) ||
                          reasoning.match(/# Decision:\s*\*\*?(INVEST|PASS)\*\*?/i);

    if (decisionMatch) {
      finalAction = decisionMatch[1].toUpperCase() as 'INVEST' | 'PASS';
    } else if (reasoning.includes('Decision: INVEST') || reasoning.includes('**INVEST**') || reasoning.includes('# Decision: INVEST') || reasoning.includes('Decision: **INVEST**')) {
      finalAction = 'INVEST';
    } else if (reasoning.includes('Decision: PASS') || reasoning.includes('**PASS**') || reasoning.includes('# Decision: PASS') || reasoning.includes('Decision: **PASS**')) {
      finalAction = 'PASS';
    } else {
      finalAction = fallbackAction;
    }
  } catch (err) {
    console.error('[Decision] LLM report generation failed:', err);
    reasoning = generateFallbackDecision(
      name, ticker, currentPrice, fundScore, sentimentScore,
      marginOfSafety, riskCount, fallbackAction, state
    );
  }

  const timeHorizon = finalAction === 'INVEST' ? '12-18 months (Graham long-term value)' : 'Not applicable';

  // --- Build sources list ---
  let rawSources: { title: string; url: string; confidence: number }[] = [];

  // Add the scraped URLs collected during the pipeline execution
  if (state.scrapedUrls && state.scrapedUrls.length > 0) {
    rawSources.push(...state.scrapedUrls);
  }

  // Fallback to news if we somehow got no scraped URLs
  if (rawSources.length === 0) {
    rawSources.push(
      ...state.newsItems.map((n) => ({
        title: n.headline,
        url: n.url,
        confidence: 0.70,
      }))
    );
  }

  // Deduplicate sources by URL
  const seenUrls = new Set<string>();
  const sources: { title: string; url: string; confidence: number }[] = [];

  for (const src of rawSources) {
    if (!src.url || src.url === '#' || src.url.includes('your-tavily-key') || src.url.includes('finnhub.io/api')) {
      continue; // Filter out invalid/mock API URLs
    }
    const cleanUrl = src.url.trim();
    if (!seenUrls.has(cleanUrl)) {
      seenUrls.add(cleanUrl);
      sources.push({
        title: src.title || 'Data Source',
        url: cleanUrl,
        confidence: src.confidence || 0.75,
      });
    }
  }

  // Sort sources by confidence descending
  sources.sort((a, b) => b.confidence - a.confidence);

  // Take top 8 sources to not overwhelm the UI/PDF
  const finalSources = sources.slice(0, 8);

  const decision: InvestmentDecision = {
    action: finalAction,
    confidenceScore: Math.min(95, Math.max(5, confidenceScore)),
    targetPrice,
    stopLoss,
    timeHorizon,
    reasoning,
    sources: finalSources,
    disclaimer: DISCLAIMER,
  };

  return {
    decision,
    status: 'complete',
  };
}

// ============================================
// Fallback report
// ============================================

function generateFallbackDecision(
  name: string,
  ticker: string,
  price: number,
  fundScore: number,
  sentScore: number,
  mos: number,
  riskCount: number,
  action: 'INVEST' | 'PASS',
  state: AgentState
): string {
  const actionLabel = action === 'INVEST' ? '🟢 INVEST' : '🔴 PASS';
  const hasThreat = action === 'INVEST' && (riskCount > 0 || sentScore < 30);

  return `# Investment Report: ${name} (${ticker})

## Executive Summary
After comprehensive analysis of ${name}'s fundamentals, market sentiment, geopolitical environment, and intrinsic valuation, the recommendation is to **${actionLabel}** at the current price of $${price.toFixed(2)}.${
    hasThreat
      ? `\n\n⚠️ CAUTION / PATIENCE RECOMMENDATION: High geopolitical risks (${riskCount} active threats) or negative sentiment signals are present. While the company's valuation qualifies for an INVEST recommendation, we strongly advise staying patient and waiting/holding off on deployment until news or geopolitical situations improve.`
      : ''
  }

## Decision: ${actionLabel}

${action === 'INVEST'
    ? `The stock presents a compelling opportunity with a ${mos.toFixed(1)}% margin of safety. Graham's fundamental checklist score of ${fundScore}/100 indicates solid financial foundations. ${
        hasThreat
          ? `However, due to active geopolitical threats or negative news sentiment, we recommend exercising patience and waiting for an optimal, calmer entry window.`
          : `Market sentiment (${sentScore}/100) suggests the stock is in a healthy accumulation zone.`
      }`
    : `The current valuation does not offer sufficient margin of safety (${mos.toFixed(1)}%). With a fundamental score of ${fundScore}/100 and ${riskCount} high-severity geopolitical risks, the risk-reward profile is unfavorable. As Graham wrote: "The essence of investment management is the management of risks, not the management of returns."`
  }

## Key Reasoning (Graham Framework)

### 1. Margin of Safety
${mos >= 30
    ? `✅ At ${mos.toFixed(1)}%, the margin of safety exceeds Graham's minimum 30% threshold, providing a meaningful buffer against estimation errors.`
    : mos >= 0
    ? `⚠️ The ${mos.toFixed(1)}% margin of safety falls below Graham's recommended 30% minimum. This exposes the investor to downside risk if intrinsic value estimates are optimistic.`
    : `❌ Negative margin of safety (${mos.toFixed(1)}%) — the stock trades above estimated intrinsic value. Graham's first rule: "Never buy a stock at a price above its indicated value."`
  }

### 2. Intrinsic Value Assessment
- Graham Formula Value: ${state.valuation?.grahamValue ? `$${state.valuation.grahamValue.toFixed(2)}` : 'Not calculable'}
- DCF Value: ${state.valuation?.dcfValue ? `$${state.valuation.dcfValue.toFixed(2)}` : 'Not calculable'}
- Blended Intrinsic Value: ${state.valuation?.intrinsicValue ? `$${state.valuation.intrinsicValue.toFixed(2)}` : 'Not calculable'}

### 3. Mr. Market Sentiment
The current sentiment score of ${sentScore}/100 (${state.sentiment?.overallSentiment || 'neutral'}) suggests ${
    sentScore > 70 ? 'excessive optimism — Graham would warn against buying into euphoria' :
    sentScore < 30 ? 'widespread fear — potentially creating a contrarian buying opportunity' :
    'balanced market emotions — neither euphoria nor panic, allowing for rational analysis'
  }. There are ${riskCount} high-severity geopolitical risks identified.

### 4. Investor Classification
This stock is ${fundScore >= 60 ? 'potentially suitable for Graham\'s **defensive investor** given adequate fundamentals' : 'better suited for the **enterprising investor** who can devote time to deeper analysis and accept higher risk'}.

## Scenario Analysis
| Scenario | Price Target | Upside/Downside |
|----------|-------------|-----------------|
| 🐂 Bull | $${state.valuation?.scenarios?.bull?.price?.toFixed(2) || 'N/A'} | ${state.valuation?.scenarios?.bull?.price ? `+${((state.valuation.scenarios.bull.price / price - 1) * 100).toFixed(1)}%` : 'N/A'} |
| 📊 Base | $${state.valuation?.scenarios?.base?.price?.toFixed(2) || 'N/A'} | ${state.valuation?.scenarios?.base?.price ? `${((state.valuation.scenarios.base.price / price - 1) * 100).toFixed(1)}%` : 'N/A'} |
| 🐻 Bear | $${state.valuation?.scenarios?.bear?.price?.toFixed(2) || 'N/A'} | ${state.valuation?.scenarios?.bear?.price ? `${((state.valuation.scenarios.bear.price / price - 1) * 100).toFixed(1)}%` : 'N/A'} |

## Conditions
${action === 'INVEST'
    ? `- **Ideal entry**: $${(price * 0.95).toFixed(2)} or below\n- **Patience Trigger**: ${hasThreat ? `STAY PATIENT: Wait for the ${riskCount} geopolitical risks or news indicators to stabilize before investing.` : 'None (market conditions stable)'}\n- **Stop loss**: $${(price * 0.85).toFixed(2)}`
    : `- **Reconsider if**: P/E drops below 15, margin of safety exceeds 30%\n- **Watch for**: Fundamental improvements in next 2 quarters\n- **Alternative**: Consider sector peers with better value profiles`
  }`;
}
